### ISSUE TITLE
Research and evaluation epic

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#1011]
[Form builder research and evaluation questions ideation session](https://easyretro.io/publicboard/KJpqjv2x5HWIX5B8IgcoLrpbdqh1/a1f6d20c-4d24-4ea5-b4c6-a15fa9a4f1e0?sort=votes)

This epic captures the data strategy, research and evaluation activities that we want to implement. 

### Acceptance criteria
**Usability testing** - @connorscarolyns 
- [x] Do people want to use the product to test their forms with users?
- [x] What is the ease of use for the JSON download, upload, and share flow?
- [x] What is the ease of use for the translation flow?
- [ ] What are the primary blockers to adoption?
- [x] Test where in the service flow we have the login
- [ ] Test key task completion rates

**Product analytics** - @srtalbot 
- [ ] Drop-off rates and product funnel (Google Analytics)
- [x] Number of support tickets opened (Freshdesk)
- [x] Response time for support tickets (Freshdesk)
- [x] Program team objectives (In go-live request flow)
- [x] If a form is currently available via PDF or new (Publishing a form flow)

**Evaluation research** - @srtalbot @connorscarolyns 
- [ ] Time a form builder spends drafting a form (comparative analysis between GC Forms and a previous process for the same form)
- [ ] Guardrail metric for time spent drafting (Metric still needs to be developed)
- [ ] Time from initial contact to a live form for GC Forms
- [x] Number of departments using GC Forms (Track via GC Email addresses for form builder primary contact)

**Comment by timarney** [comment]
Closing as stale --- re-open as you see fit.
