### ISSUE TITLE
Form builder - Client sign-up and approval

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#1036]
## Objective 1, Key result 4:
Form builders are able to sign-up and login to publish their forms. (Oct / Nov)

**Goals**
- We should not be approving publishing for each form, just the first time someone wants to publish a form. 
- Validate that a form builder has a government of Canada email address
- Restrict publishing until a form builder has an approved account
- Outline the risks associated and treatment approaches. The product should not increase existing risks for harm to the government of Canada's reputation or operations.

**Definitions:**
- Primary contact: The person signing up for an account that is building the form
- Service owner: a Manager or higher, a contact we can get in touch with if we need to escalate a violation of the terms and conditions

**Background**
[User flow for form builder](https://www.figma.com/file/dbezuEglWNQ8qyO64eJJiA/v1.-Form-builder?node-id=242%3A5617)
[Service flow documentation](https://docs.google.com/document/d/1G9-MSVzgJ-5ANCEhYNbDGBrjhYBokc2gZGeYkimkuQ8/edit#)
### Requirements for publishing a form
- [x] We validate the primary contact (form builder) has access to the email they provide.
- [x] The primary contact accepts the terms and conditions
- [x] They provide a contact of a Service Owner
- [x] Their program objectives for using GC Forms
- [x] That email is an acceptable Government of Canada email (Manual check by the support team)
- [x] They have an approved account
- [x] They tell us whether this is a new form, or one they are digitizing from a PDF.

### Business requirements
- [x] System meets WCAG 2.0AA standard
- [x] System is available in French and English
- [x] System provides error messages
- [ ] Update risk register for impact, likelihood, and treatment approaches.
- [ ] Service owners are able to recover accounts on which they are listed if a primary contact is no longer available. (Manual process with platform support)
