### ISSUE TITLE
Pre-launch testing epic

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#1251]
**Description:** This is testing we. want to complete by the end of sprint 7, Nov 21 - Dec 2nd. After this we will [triage](https://docs.google.com/document/d/1rqzafXy3I236vryBMBGPYojalSSxLSw8LC4pSRb8gW8/edit#heading=h.w2rwj5yfsnf4) and prioritize the issues to identify what to take on in our following sprints. 

### Pre-launch acceptance criteria:
- [x] 3rd party pen test - Facilitated by Core Services @Abi-Nada 
- [x] 3rd party accessibility audit and manual testing at the WCAG 2.0 AA level - Facilitated by AAACT and a Forms dev
- [x] Bilingual usability testing - @connorscarolyns @Abi-Nada 
- [x] Go-live process and support testing - @ioanacontu @srtalbot 
- [x] Build and publish five real forms to collect information
