### ISSUE TITLE
Tech Debt: Repo folder clean up and documentation

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#1371]
### Instructions
- Decide in sprint planning which of the checklist items will be worked on until it is complete. (Proposed approach)
- Identify a lead for the tech debt discussions. This person is responsible for coordinating meetings, discussions, and documenting decisions. 

### Tech debt list

Clean up in the following folders:
- [ ] Component folder
- [ ] Library folder
- [ ] Public assets
- [ ] Testing locations
- [ ] README and Dev documentation
- [ ] Review and update changelog
- [ ] Typescript cleanup
- [ ] Review approach to translations

### Component folder
We currently split up our components by where they function. I believe this is fine but it can certainly be confusing to a new developer on Forms ( or even having returned after a vacation ). Several components however are inconsistent in how they are structured . Typically each component has a folder but some components are defined as single files in their respective function folder. For example some global components 

https://github.com/cds-snc/platform-forms-client/tree/develop/components/globals

Some component folders also have an index.ts but others do not. This means that how you import components varies differently across the codebase and this adds a lot of cognitive load.

### Library folder
Files in the lib folder should be organized in folders based on their function. When you go into the lib folder it’s very hard to actually determine what each file roughly does. We need to think about structuring our lib folder by functionality so related code is grouped together and one can determine roughly what the files do 

https://github.com/cds-snc/platform-forms-client/tree/develop/lib

### Public assets
The public folder needs to be looked over. Specifically which assets are used and which can be removed. 

https://github.com/cds-snc/platform-forms-client/tree/develop/public/img

Assets in the img folder need to be revised where they are used and they should be grouped in folders according to what they are for. This will help us identify which assets can be removed such they are not bundled in our build and contribute to bloat. 

We also have scripts that can probably be removed. Such as for example ie polyfills 

https://github.com/cds-snc/platform-forms-client/tree/develop/public/static/scripts/polyfills

Making sure we are lean on what assets are included in the production bundle will increase the performance of our application 

### Testing file locations
Tests should ideally be located near the code that they test such that they are easily associated. We collocate test files with our react components but not others such as in our lib folder. This increases cognitive load in trying to find what tests what.

### README and Developer documentation
Aim to onboard new developers quicker by providing inline comments and updating the readme. 

### Changelog
Review the current changelog and coordinate with product to identify how to make meaningful updates. 

### Typescript clean up
Our codebase is still not completely typescript converted. There are several components that are written in JS. For example 

https://github.com/cds-snc/platform-forms-client/blob/develop/components/globals/LanguageToggle.js

Furthermore we are not consistent in where we are defining types and how we are exporting them and importing them i.e. defining component props interfaces in our lib/types folder vs at the component file 
https://github.com/cds-snc/platform-forms-client/blob/develop/lib/types/component-utility-types.ts

This can make modifying code pretty difficult especially if you need to modify what it inputs and outputs. While our IDEs simplify this for us . Jumping between files inconsistently causes a lot of cognitive load

Furthermore we should evaluate on whether or not to use TypeScript on our lambdas to have further confidence when modifying them 

https://docs.aws.amazon.com/lambda/latest/dg/lambda-typescript.html

### Approach to translations
Our translations are roughly divided into JSON files based on where they are used. 

https://github.com/cds-snc/platform-forms-client/tree/develop/public/static/locales

However we could probably better organize them into folders so it’s very clear as to to where they are used. Furthermore we need a mechanism to identify untranslated strings. Not addressing this means we can potentially fail on our OL obligations by missing translations which have gone undetected

**Comment by srtalbot** [comment]
@bryan-robitaille @timarney - can you check to see what is still relevant in this tech debt, please
