### ISSUE TITLE
Review user flows

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#1382]
Review the user flows to update the links and routing to support key tasks, including:

- [ ] Entering the product from the product marketing page (future state) (Won't do)
- [x] Entering the product from: https://forms-staging.cdssandbox.xyz/ (P1c)
- [x] Drafting a form (Won't do)
- [x] Signing-up (Won't do)
- [x] Previewing a form (P4a)
- [x] Test the form data delivery (P3)
- [x] Setting and testing their response delivery email address (P4b)
- [x] Sharing forms (P5)
- [x] Translating forms (P2a)
- [x] Requesting to publish (Won't do)
- [x] Review superadmin flow to provide access to publish (Test with support)
- [ ] Publishing (Won't do)
- [ ] Viewing forms (Won't do)
- [ ] Deleting forms (Quick review by design of what is already implemented)
- [x] Persistence of French interface (P2b)
- [x] Paths that take you outside of the application. Review for loss of data, make the link an open in a new tab. (P1b)

Unhappy path to review:
- [x] Losing form data (P1a)

### Known issues:
- [ ] Checklist: When all items were not checked off, users struggles to figure out what they had to do. They wanted more context in the items and links to the pages that needed fixing
- [ ] The page contextual navigation items do not look interactive items, users hesitated, or in some cases, did not click on them
- [x] French interface did not persist when moving from core application to builder and back
