### ISSUE TITLE
PBMM Release 🎉🎉🎉 (Target date Aug 21st)

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#2362]
The looong list of items that we need to do before launching Protected B, medium integrity, medium availability.

### Security work
[iATO brief to the executive director of platform, CDS Security, and Platform SRE](https://docs.google.com/document/d/1R7Wko0Mn9e9d-xcd8fDFVFIsKVexU-YnnPUvstv10Ns/edit#heading=h.vbll7fi9thtu)
- [x] 2FA
- [x] Logs for escalating privileges 
- [x] Deactivating a user @timarney 
- [x] Upgrading Terraform Provider to unblock implement WAF spam prevention rules. @falila 
- [x] Reviewing and creating alarms @bryan-robitaille 
- [x] Implementing on-call rotation with schedule for next two months @ioanacontu 
- [x] Threat modeling exercise with Security @maxneuvians 
- [x] Upgrade password reset flow @timarney - Release on Aug 16th
- [x] Update the system description @srtalbot 
- [x] Update the security assessment @srtalbot 
- [x] Update the risk register @srtalbot 
- [x] Update the statement of sensitivity @sarahhobson 
- [x] Flag which ATO policy and procedure documentation needs to be updated - can be done at a later date. 
- [x] Updating the “Contact Us” form - coordinate with Jose (Dev + Jose) @thiessenp-cds 
- [x] Action items from the table-top exercise (Carolyn + Anik +SR)
  - [x] Confirm with support where the deactivate documentation should live. 
- [x] QA Testing on Security questions and deactivate user flow
  

### Pre-launch work
- [x] Launch plan drafted by Growth and approved by Head of and PM @jose
- [x] Draft communications to clients @jose @srtalbot 
- [x] Send out communications to let current users know they will need to create security questions - Monday Aug 14th
- [x] Finalize privacy notice @sarahhobson 
- [x] Update Product screens to reference PB @samsadasivan 
- [x] Implement PB data classification in settings and restrict PB to response database only @samsadasivan 
- [x] Finalize content and visuals on the product marketing page @jose-cds  
- [x] Finalize GA funnel analysis @daine 
- [x] Update the download and confirmation flow for test form responses @daine 
- [x] Review work with SRE and Security @srtalbot @bryan-robitaille 
- [x] Identify individuals who need access to AWS Prod console and get to least privilege access @bryan-robitaille @timarney @srtalbot (Card created)

### Release checklist - Start your engines, get those PRs ready on staging
- [x] Update privacy notice @devs
- [x] Update user screens and HTML data output to refer to PB @devs
- [x] Brief and get approval from the Executive Director of Platform and Head of SRE @product
- [x] Finalize ATO package that we can share with clients and how we will share, coordinate with Growth and support @product (Card created)
- [x] Review Forms marketing material

### Production release
- [x] Book a time for EVERYONE to get together - let's. celebrate.
- [x] Release to production for PB - Monday the 21st at 1pm @craigzour 
- [x] Go live with the product marketing page - Monday the 21st 2pm @jose-cds 
- [x] Send the client communications - Monday the 21st at 2pm @jose-cds

**Comment by srtalbot** [comment]
ATO Policy and procedure documents that need to be updated before circulation:
- Audit policy
- Secure Software Development Cycle
- Access Control and Authentication Management
- Public Content Policy
- Contingency Plan
- Disaster recovery
