### ISSUE TITLE
⭐ Feature: Security questions / Password Reset

### ISSUE THREAD

**Issue by timarney** [cds-snc/platform-forms-client#2401]
Feature branch 
👉  https://github.com/cds-snc/platform-forms-client/pull/2415

- [x] #2453
- [x] #2463
- [x] #2465
<hr>

- [x] #2452
- [x] #2464

- [x] Add dropdown to navigation - @dsamojlenko  https://github.com/cds-snc/platform-forms-client/issues/2412

https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=1770-64311&mode=design&t=VQ8JIJSa10IrJcc1-0

<img width="400" alt="Screenshot 2023-07-18 at 10 26 38 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/c366a198-8738-4fcc-a7d7-95d5040777e3">

<hr>

- [x] Setup profile page @timarney https://github.com/cds-snc/platform-forms-client/issues/2413

https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=1908-63240&mode=design&t=VQ8JIJSa10IrJcc1-0

- Setup the base layout for the "profile page"
- Edit links to be handled in a separate task 
- Security questions etc... can be placeholder text
<img width="500" alt="Screenshot 2023-07-18 at 10 23 41 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/b6eaebf0-0c3d-42b9-86f4-be75f5a89b9d">

<hr>

- [x] Add security question modal @thiessenp-cds https://github.com/cds-snc/platform-forms-client/issues/2418
 - this should accept a prop for question id + populate and update accordingly
 
 
<img width="500" alt="Screenshot 2023-07-18 at 10 28 46 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/267f092b-99bd-4604-bb68-3c519a4e1b69">

<hr>

- [x]  Code to check if we need to land you on the security questions page (i.e. security questions haven't been setup yet) @timarney https://github.com/cds-snc/platform-forms-client/issues/2428

https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=1783-78150&mode=design&t=qQaC6Nh2jNG90qHQ-0

<img width="735" alt="Screenshot 2023-07-21 at 8 34 55 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/5ca91f8a-a1e4-4bcc-ad68-eb461deb9150">

<hr>

- [x] Security questions form page @thiessenp-cds https://github.com/cds-snc/platform-forms-client/issues/2417

 https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=1783-78150&mode=design&t=6gp4SuVZPd75grfc-0

<img width="491" alt="Screenshot 2023-07-18 at 12 18 07 PM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/4dcdeb46-7fd8-4b9b-b97a-caeb4cf78ac8">

<hr> 

- [x] Answer security questions page (before password reset) @timarney https://github.com/cds-snc/platform-forms-client/issues/2425
- Needs API to look up / validate

https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=1770-63029&mode=design&t=z5tq6uY6OQaxr5BN-0

<img width="400" alt="254876878-31454253-67a0-42f7-a257-c8b47771bb01" src="https://github.com/cds-snc/platform-forms-client/assets/62242/b714e1a7-aa0a-4581-aeec-7d058c538468">

<hr>

- [x] #2450
- [x] #2451

**Comment by timarney** [comment]
@bryan-robitaille @craigzour have either of you started thinking about how we'll store user questions & responses in the database yet?  Thinking about the relations / tables / structure etc...

**Comment by craigzour** [comment]
> @bryan-robitaille @craigzour have either of you started thinking about how we'll store user questions & responses in the database yet? Thinking about the relations / tables / structure etc...
> 
> We can likely start building out some of these `views` and connect them once we have those other pieces figured out.

That is on my plate for when I am done working on my current task (will probably start looking into it early next week).

**Comment by timarney** [comment]
- [ ] Setup profile page

- Setup the base layout for the "profile page"
- Edit links to be handled in a separate task 
<img width="500" alt="Screenshot 2023-07-18 at 10 23 41 AM" src="https://github.com/cds-snc/platform-forms-client/assets/62242/b6eaebf0-0c3d-42b9-86f4-be75f5a89b9d">


See
https://www.figma.com/file/89fRce4gmy64UIArSZoAM8/v3.-GC-Forms-(builder-and-vault)?type=design&node-id=1908-63240&mode=design&t=VQ8JIJSa10IrJcc1-0

**Comment by timarney** [comment]
Merged in release v3.3.0

**Comment by timarney** [comment]
Shipped.
