### ISSUE TITLE
Bug Bash🐛

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2569]
### Description:

This epic is part of a dedicated "Bug Bash Sprint" with the goal of significantly reducing the bug backlog.

This epic aims to address the backlog of bugs that have accumulated in our application over time. It's a focused effort to enhance GC Form's stability and user experience by systematically identifying, prioritizing, and fixing bugs.

### Acceptance Criteria:
- [ ] All known bugs are documented and categorized.
- [ ] Bugs should be prioritized/labelled based on a defined criteria (e.g., severity, impact) by the PM & DM.
- [ ] Bug fixes are tested and validated before being marked as resolved.
