### ISSUE TITLE
O3: Improve the response database

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#2637]
### Context
The number one blocker for future clients is the availability of data in a spreadsheet format.

The number one pain point for current users is the confirmation flow. 

For more information on the user stories, value, and approach, see the [opportunity canvas.](https://miro.com/app/board/uXjVMv81Ezo=/?share_link_id=378499319018)

### Jobs to be done
**Program administrators:**
When multiple form submissions are provided by form filers
I need to be able to:
- Take multiple form submissions and integrate them with a spreadsheet
- Quickly check to see if there are errors in the form submissions (like a French character not being rendered correctly)
So that I can quickly and efficiently get my data into a spreadsheet in the format that is easiest for me to work with.  

**Auditor**
When a member of the public is grieving a decision made about them by the government
I need to ensure that the data did not change at all when being processed by GC Forms.
So that the government can show we did not change the data provided by the member of the public. 

*limitation: GC Forms is responsible for the data up to the point that a program administrator takes ownership of the data. 

### Scope
- Provide users with the ability to choose their data format
- Improve the findability of setting a form to protected B.
- Provide responses that seamlessly integrate with Microsoft excel, and does not require the support of a developer.
- System maintains a Protected B confidentiality, medium integrity and availability designation.
- System maintains high confidence in data reliability, so that it is not corrupted or lost during delivery to the client.
- Reduce the friction of the confirmation flow for HTML and Spreadsheet data outputs

### Definition of done
- [x] Screens and pages work on MS Edge and Chrome.
- [x] Screens and pages work on Tablet and desktop.
- [x] Content communicates any system limitations and errors.
- [x] Spreadsheet integration works for a first-time download.
- [ ] Spreadsheet integration works when downloading into an already existing response table. 
- [ ] Spreadsheet integration works with GC Notify's CSV import feature
- [ ] Spreadsheet output can support future features, including: file attachments, repeating question feature, and conditional logic.
- [x] Clients have an official record of the responses that we know has not been changed due to data loss, corruption, or manipulation. (e.g., a hashvalue in the HTML output that checks form data)
- [x] Risks to losing form response data are treated (mitigated, avoided, accepted, or transferred), with residual risk documented and signed off on.  
- [ ] Pages and screens meet WCAG 2.1 AA requirements.
- [ ] Accessibility limitations of the spreadsheet output are documented and published for clients to read.
- [x] End-to-end testing for functionality and user flows
- [ ] Track: Number of times a data format is used.

**Comment by srtalbot** [comment]
Next steps for prototyping:
- Review the mental model of "confirm" and prototype a move to "confirm and delete"
- Create new user journies for selecting a data output format.
- Prototype, assess accessibility and security, and estimate effort for HTML tables. 
- Prototype, assess accessibility and security, and estimate effort
