### ISSUE TITLE
Product evaluation and dashboard

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#2725]
[Current airtable for reference](https://airtable.com/appUJnNvHQoZoe0G4/pagixJnRUc2wbIglm)

### Metrics:
- [x] Total number of forms (exclude CDS forms)
- [x] Time series data for number of forms
- [x] Total number of forms by classification (exclude CDS forms)
- [x] Total number of **live** forms (exclude CDS forms)
- [x] Total number of **live** forms by classification (exclude CDS forms)
- [x] Number of forms by department
- [x] Number of accounts with permission to publish (exclude CDS accounts)
- [x] Number of accounts with "manage all forms" or "manage all users" permission
- [x] Top 5 forms by number of submissions
- [x] Product up-time

### Acceptance criteria
- [ ] Ideation on how we might [get better data quality for live forms](https://gcdigital.slack.com/archives/C0117FN8G9K/p1695758892509409?thread_ts=1695743365.991529&cid=C0117FN8G9K)
- [ ] Create end-points for data so that we can build a dashboard or push the data
- [ ] Discussion on how to visualize the data and which software would be best (could be in-app, or something like PowerBI)
- [ ] Do we need some sort of permission added?

**Comment by srtalbot** [comment]
Duplicate card, closing
