### ISSUE TITLE
Infrastructure Cleanup

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#2844]
# Description

This card outlines the process for streamlining our current infrastructure to improve efficiency and eliminate any redundant or outdated components. The goal is to ensure our infrastructure is lean, up to date (as much as it safely can be in 2 sprints!), and documented, with all changes properly tested and verified.

## Work Items:
 - [ ] Separate out  all services that can be created locally in localstack so true local testing can take place.
   - [x] Back office Lambdas
   - [x] S3 Buckets
   - [x] Secrets Manager
   - [x] File Upload Scanning
 - [ ] Ensure event triggers are automatic between back office lambdas and do not require manual triggering.
 - [ ] Configure AWS SAM to leverage terraform so development on Lambdas can continue to leverage real time builds.
 
## Localstack could include the following services as well if we buy Pro licenses:
- [ ] RDS
- [ ] Elasticache (Redis)
- [ ] Cognito

This would remove any reliance on leveraging Staging services and manually running docker containers for local development.

## Acceptance criteria:
- [ ] Review the current infrastructure setup to identify redundancies, outdated services, or configurations
- [ ] Identify any dependencies that need to be updated or removed

**Comment by Abi-Nada** [comment]
@craigzour to test the local env now that Bryan pushed an update
