### ISSUE TITLE
Data retrieval API Discovery

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#3591]
### Description:
**Objective two:** Reduce manual data processing for clients and support high volume services by data retrieval via Application Programming Interface (API).

**Key result:** Conduct an initial discovery and design document explores a Forms data retrieval API that could, in the future, integrate with a Platform API gateway 

### Definition of Done
- [x] Alignment with Strategic Delivery, Notify, and Forms on roles and responsibilities [(Document)](https://docs.google.com/presentation/d/1B8Z-ts6LtrLSf9r0HwzyFy0b8EsHuaOEULwIT3Qk3to/edit#slide=id.p1)
- [x] Review of [GC API guidance](https://www.canada.ca/en/government/system/digital-government/modern-emerging-technologies/government-canada-standards-apis.html) to identify areas of agreement or intention to diverge. 
- [x] Coordinate with Core and Strategic delivery on what a proposed API gateway would look like by reviewing [GC guidance.](https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/enabling-interoperability/api-guidance/gateways.html)
- [x] A technical design document that outlines the proposed architecture for a GC Forms data retrieval API, which includes:
  - [x]  Version 1: The initial GC Forms architecture without a central API
  - [x]  Version 2: A general strategy for migration to a central API gateway once a team has been staffed
  - [x]  Highlight areas of high effort for migration, duplication of work, or security issues. 
 - [x] Review architecture with users to validate high risk assumptions (ones we are less than 60% sure about, or have significant impact on the security of the API)
