### ISSUE TITLE
Conditional Logic marketing strategy

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3603]
### Description:
Develop and communicate a marketing strategy focusing on the transition to new features (Conditional Logic).

How might we set up our existing power users for success (when they're struggling with a change in their mental model of the product)

**Comment by samsadasivan** [comment]
https://docs.google.com/document/d/1nF5YW6lLQMLGdyljwxtKqUH4FoYaebw71w_Nv0Kt2Ew/edit#heading=h.ru24wrgw4m14

^
- New features 
- Features that have been changed

**Comment by Abi-Nada** [comment]
Working doc:
https://docs.google.com/document/d/122JG-7K5mz77rQh2-6RqnJAMefSwsUjLDukxY9lPkYg/edit#heading=h.v4cgm48ylses

**Comment by anikbrazeau** [comment]
## Comms tactics for release

- [ ] Banners (to set expectations in-app) #3849
- [ ] One-pager (to summarize changes)
- [ ] Mailing list (to send updates to subscribers) 
- [ ] Guidance articles (to outline how to use new features) #3883
- [ ] Demo (to walk through changes in real time)
- [ ] Deck (to give an overview of the product)  
- [ ] Homepage and Feature page (to highlight capabilities) #4017
- [ ] Templates (to utilize/maximize all features and best practices) #4006
- [ ] Social media
- [ ] CDS newsletter

**Comment by jose-cds** [comment]
FYA that is a non-exhaustive list of tactics. Keenan and I are still working on what will get prioritized for August 6th and what will be prioritized for later in August. I'll share-back on what we'll be prioritizing next week.

**Comment by Abi-Nada** [comment]
Conditional Logic Promo Plan: https://docs.google.com/document/d/1d_ZEuIY8NDU5QNIqjvqj45t8iJ5-INOXqz8wkh79KYk/edit#heading=h.nte23a69fsnb

**Comment by Abi-Nada** [comment]
Closing out this card, and we can split out specific product team tasks into different cards
