### ISSUE TITLE
Conditional Logic Concept Clarity and Guidance

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3604]
### Description:

Refine product content to make the experience as clear as possible.
Create public documentation and guidance for how to use conditional logic.

### Product content:
- [x] Glossary of terms for the new product features
- [x] Product content refinement English ---> #3848
- [x] Product content refinement French  ---> #3848
- [x] Testing bugs in the logic and tree views
- [x] Autoflow ---> #3819
- [ ] Alerts and errors ---> #3846
- [ ] Banner ---> #3849
- [ ] Content improvements based on tests --->

### Guidance:
- [ ] Outline a strategy for communicating new features
- [ ] Work with growth and support on specific comms materials and docs
- [ ] Documentation covers how to set up and use conditional logic
- [ ] Include examples and best practices
- [ ] Documentation is published as a Guidance page

**Comment by Abi-Nada** [comment]
Conditional Logic Feature doc: https://docs.google.com/document/d/1nF5YW6lLQMLGdyljwxtKqUH4FoYaebw71w_Nv0Kt2Ew/edit#heading=h.ru24wrgw4m14

**Comment by anikbrazeau** [comment]
https://github.com/cds-snc/platform-forms-client/pull/3818

**Comment by anikbrazeau** [comment]
Closing as covered in other new broken down cards
