### ISSUE TITLE
Conditional Logic Release

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#3830]
### Documents:
[CL Release Roadmap
](https://docs.google.com/document/d/1U_VTagCJt1l3svZ_RahaUGHOzAbu_YofOse_8EmCJOo/edit#heading=h.a4v429ecfh2r)
### Things to validate:
- [x] Functionality Testing (CDS Internal Testing, QA Testing, Diary Study)
- [x] A11y testing (Pete's internal audit, Fable testing)
- [x] Data output and integration with client workflow (Diary Study, QA Testing)
- [x] Does the schema work? (Dev testing) #4007 #4015
- [x] Backwards compatibility (Dev testing) #4022
- [x] Testing data loss scenarios (Dev testing, QA Testing)
- [x] Bilingualism (testing ratio 7:3 EN/FR users)
- [x] Security (product x tech sync)

### Milestones:
- [x] Implement findings from Fable testing (Critical and severe issues only)
- [x] Implement findings from Internal CDS functionality testing (Critical and severe issues only)
- [x] Implement findings from Diary Study research with Forms clients (Critical and severe issues only)
- [x] 1.5 weeks for a dev to test backwards compatibility + validate that the schema works (QA testing at the same time)
- [ ] Brief to policy (confirm no impacts to SLA or ToU)

### Client comms (Setting expectations for before and after release: drafting communications/marketing strategy): 
- [x] UI update (pre-release): Create a banner in the product to let clients know that a change is coming #3849 
- [x] UI update (post-release): Banner on prod -> something like "Branching logic is new to GC Forms. If you find bugs, contact us to report them etc."
- [x] Guidance documentation on using CL is translated and published #3883 
     - https://articles.alpha.canada.ca/forms-formulaires/setting-up-form-logic/ 
     - https://articles.alpha.canada.ca/forms-formulaires/fr/configurer-formulaire-avec-logique/ 
- [x] Mailing list update is drafted and translated (Growth) #3603
- [x] Run through feature with Growth and Support
- [x] GC Forms marketing site updates: Update to point to the Strategic roadmap (Growth)
- [ ] Update Strategic Roadmap

### Prod release:
- [ ] Flag to Growth once release is done, to send out client comms
