### ISSUE TITLE
Coordination with API prototyping partners

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#3889]
### 1. Information gathering mode - light touch with devs. Gather information about systems. 
- [x] Conduct [survey](https://docs.google.com/presentation/d/1GZF0kxfANV3N4fuNXFpmYxa4Ly6IsNhLO03T1BuDX30/edit#slide=id.g1f2ebf01fcd_8_11285) to identify potential prototyping partners and high-level requirements
- [x] Select 3-5 [partners](https://docs.google.com/presentation/d/1GZF0kxfANV3N4fuNXFpmYxa4Ly6IsNhLO03T1BuDX30/edit#slide=id.g2e6eafa6d42_2_76)
- [x] Establish contact with all partners and identify terms of prototyping.
- [x] Identify an approach to roll out API functionality incrementally. 

### 2. Prototyping mode - Work with them to integrate and test. 
- [x] Implement an authentication flow
- [x] Implement the API server (basic functionality)
- [x] Test initial integrations with partners and get feedback 
- [x] Identify additional steps required to get the data into a target system that partners will need to develop (e.g., a plugin for MS Sharepoint or PowerBI). 

### 3. Implement a form - Work with the team to launch a form that uses the data retrieval API
- [x] Identify a way to share how partners were able to integrate with a variety of systems
- [x] Get a live form with each prototyping partner
- [x] Start to test self-service patterns

**Comment by srtalbot** [comment]
[Summary for API prototyping partner work to date](https://docs.google.com/document/d/11oXOoX-khFRzGTLhzayqDMtLWSb7fe2OEgjdb5fhHlE/edit?tab=t.0#heading=h.hft253dam5cv)
