### ISSUE TITLE
API: Identity Provider for request authentication

### ISSUE THREAD

**Issue by patheard** [cds-snc/platform-forms-client#3927]
# Summary
The form response retrieval AP requires an IdP that supports the OAuth private key JWT authentication flow.  [Zitadel](https://github.com/zitadel/zitadel/) has been selected as the IdP.

The following work will be required:

- [x] Terraform to setup and managed the IdP AWS resources.
- [x] GitHub workflow changes for the Terraform.
- [x] GitHub workflow changes to build and push the Zitadel Docker image. 
- [x] Deploy and test the IdP in Staging. 

# Related
- https://github.com/cds-snc/platform-forms-client/issues/3925
