### ISSUE TITLE
Add link to roadmap in footer

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#3928]
**User story**: Persona based
As a user or prospective user of GC Forms
I need to know what's coming up in terms of features
So that I know whether the product will meet my needs

**Story context**
https://gcdigital.slack.com/archives/C0580BGPWNN/p1718142317485849?thread_ts=1718139461.294289&cid=C0580BGPWNN

**Roadmap link**

EN: https://trello.com/b/napn8wCR/gc-forms-strategic-roadmap-en?search_id=6740e942-ec1c-4f99-af2a-029ee3f41484

FR: https://trello.com/b/MaWVk9V5/formulaires-gc-strategie-fr

**Acceptance criteria**
- [x] *feature* provides equal service in French and English.
- [x] *feature* works on Chrome, Firefox, Edge, Safari, and Opera.
- [x] *component* provides and auto-fill response if the field is saved on the end-users browser.
- [x] *component* provides error messages and validation.
- [x] *goal* can be completed using a screen reader.
- [x] *visual elements* observe colour contrast requirements. 
- [x] manual accessibility testing meet WCAG 2.1 AA requirements.
- [x] risk register is updated to reflect new risks and their treatments. Treatments are implemented or a new card is created.
- [x] *feature* collects the data intended, stores, and submits it in the correct format via email, API, or other retrieval method

**Comment by anikbrazeau** [comment]
Done! 
<img width="1216" alt="Screenshot 2025-01-02 at 10 16 55 AM" src="https://github.com/user-attachments/assets/c3e148cc-9556-4007-b1f0-f47e86d631c4" />
