### ISSUE TITLE
Form templates opportunities and updates

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/platform-forms-client#4006]
## Description

Update templates available including branding form with new conditional logic features and pages

More specifically: 
- #4238 
- #4926 

## User story

As a form builder using a template to build a form for the first time
I expect the form to use all the features available and follow best practices
So that I can optimize the experience for end users

## Main links

- ### [Better forms, quicker with common form patterns](https://docs.google.com/document/d/1FweP75wkZgFXjoMs1yFZkTDuAUnhaZwD8qnb42oegG4/edit?tab=t.0#heading=h.rmutho8gh3fv)
- ### [Forms use cases](https://airtable.com/appx32sGoxl82EOPu/tblB2AVQiLnhoaQGY/viwmtZMqyJagg7oom?blocks=hide)

### Templates
https://articles.alpha.canada.ca/forms-formulaires/templates/

<img width="1012" alt="Screenshot 2025-01-02 at 3 50 44 PM" src="https://github.com/user-attachments/assets/38e88bea-6ca0-40bd-a5f1-e668b2affd41" />
<img width="989" alt="Screenshot 2025-01-02 at 4 09 28 PM" src="https://github.com/user-attachments/assets/857a51bd-a249-400e-9cd9-fe6bc927163a" />

## What's involved

Uncover opportunities:
- [x] Identify potential new templates
- [x] Assess form component combinations / patterns
- [x] Follow up on analytics / measurement
- [x] Revisit what we have and what we know so far
- [ ] Republish branding form #4923 
- [ ] Publish new boilerplate form # 1 #4238 
- [ ] Publish new boilerplate form # 2 #4926
- [ ] Publish new boilerplate form # 3 TBD
- [ ] Republish contact form
- [ ] Republish accesibility feedback form
- [ ] Republish reporting form
- [ ] Update old forms (close + update link + redirect)
- [ ] Update existing template guidance article with new links

**Comment by anikbrazeau** [comment]
### Plan for development of  form examples / exemplars 
- [ ] Identify most common forms or form parts that could be reused across teams and departments
- [ ] Review past research / knowledge
    - https://docs.google.com/spreadsheets/d/1JRsTSJifDA98fH9wtQQoBnruRvIw-uO4skjodgughfo/edit?gid=0#gid=0
    - https://docs.google.com/spreadsheets/d/1a59iHg84muidfimnkoz5N9HQzrVueWjMEjCQI4W6GzY/edit?gid=374932259#gid=374932259

**Comment by anikbrazeau** [comment]
https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/gh/cds-snc/platform-forms-client/4238

**Comment by anikbrazeau** [comment]
Identify: 

- [ ] Security screening form
- [ ] Forms most used on GC Forms
- [ ] Forms that repeat in every department
- [ ] Patterns of component combinations, ways to structure inputs

**Comment by anikbrazeau** [comment]
Potential patterns/templates to consider:

#4896 
#4898 
#4899
#4900 
#4903

**Comment by anikbrazeau** [comment]
Forms

https://docs.google.com/spreadsheets/d/1HtH_gg6m4symBY6JhxEJxRSZji898Cvi/edit?gid=1559964234#gid=1559964234

https://docs.google.com/spreadsheets/d/1a59iHg84muidfimnkoz5N9HQzrVueWjMEjCQI4W6GzY/edit?pli=1&gid=374932259#gid=374932259

https://docs.google.com/spreadsheets/d/1JRsTSJifDA98fH9wtQQoBnruRvIw-uO4skjodgughfo/edit?pli=1&gid=0#gid=0

https://www.tbs-sct.canada.ca/tbsf-fsct/index-eng.asp

**Comment by anikbrazeau** [comment]
**Decision**: Create 3 boilerplate forms

- Grants and contributions
- Security clearance
- Expression of interest
