### ISSUE TITLE
API V2.0.0 Self-service

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#4372]
### Version 2.0.0
User segment focus: Infrastructure developers

**User flows:**
- [x] Generate an API key
- [x] Agree to security requirements
- [x] Revoke an API key and form ID(?)
- [x] Provide information on the different data delivery methods
- [x] README file with API key
- [x] Small updates to the Support form to include branching for end-users, devs, or form builders (including a request to increase the rate limit for a form)
- [x] Basic system information on the responses page (API Status and Number of problems reported with a response)
- [ ] Consistent machine readable tag, label, or ID for a given question that will not change. 
- [x] An endpoint that notifies clients via the API that there are new form submissions
- [ ] A way to easily map form questions from the Template to form answers
- [x] API documentation published on the web in french and english
- [x] Notifications via the API that responses are being throttled
- [ ] Audit logs available in Athena or RDS for actions taken on a form:
  - [ ] A list of all actions taken on the form (created, updated, published, closed, response downloaded, date, time, user ID)
- [ ] **Explore** security enhancements the API key hand off between the form builder and infra dev hand-off for draft forms. 

**Out of scope:**
- Switching live forms from download to API
- Switching live forms from API to download
- A list of responses downloaded in the "response download" screen
- Throttling alerts in the "response download" screen
- Building our own plugin connectors to MS 365 apps (though we will work with partners to understand and help them)
