### ISSUE TITLE
Conditional logic: show or hide questions based on previous responses

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#443]
**User story**: Persona based
As an end-user 
I need to see only the questions that apply to me
So that I can focus on the only the information that I need to provide

As a program administrator building a form
I need to show or hide a question based on the previous response of an end-user
So that I can collect the information I need to process a form

As a program administrator processing a form response 
I need the data in a format that is interoperable with an email based process
So that I don't have to read through multiple blank responses

As a program administrator processing a form response
I need the data in a format the is interoperable with my case management system
So that I don't have to transform the data into another schema or format

As a program administrator
I need to make a component required (or not) based on the previous answer of an end-user
So that I can collect the data I need to process the form
(E.g.: if an end-user selects their preference is to receive updates via email instead of SMS, then the email field needs to be required, and the SMS field does not.)

**Story context**
[Preliminary tech analysis](https://docs.google.com/document/d/1U1oDHZVUQPVEh1ZFD8xwDF79eRYga7iirQ7lNxWW274/edit)

**Acceptance criteria**
- [ ] dynamic changes work on Chrome, Firefox, Edge, Safari, and Opera.
- [ ] input fields provide an auto-fill response if the field is saved on the end-users browser.
- [ ] only fields shown based on previous answers provide error messages and validation.
- [ ] conditional questions are hidden from screen readers if not applicable.
- [ ] conditional questions are read out by screen readers if applicable.
- [ ] manual accessibility testing meet WCAG 2.1 AA requirements.
- [ ] risk register is updated to reflect new risks and their treatments. Treatments are implemented or a new card is created.

**Design documentation**
- [ ] Guidance on the number of recommended questions per page
- [ ] Wireframes for pages, navigation, and review
- [ ] User flow diagram

**Comment by connorscarolyns** [comment]
https://www.figma.com/design/2bmknDRpZXN3lwqhs7mqNH/Conditional-logic-MVP-(Groups%2C-Dynamic-fields%2C-Branching)?node-id=1167-4460&t=iqZ9E1cgafz8XvQ7-4

https://www.figma.com/design/i3gZjJ27uTDKEFYMRZHRrh/Conditional-logic---Disco?node-id=332-13219&t=s1eLvrWd9GTeWDON-4
