### ISSUE TITLE
Saving progress when completing a form

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#448]
**User story**: Persona based
As an end-user
I need to be able to save my progress 
So that I can return to compete the form at a later time
So that I have confidence that the work I am completing will not be lost
So that if an error occurs I can return to my previous answers

**Story context**
[Pre-design document design document](https://docs.google.com/document/d/14mRHpF50oUg-hwVwxaNTlJQ0n5_XPrIMmKXMvvwVKIY/edit) (tech scoping work)
[Example of a contribution form for Accessibility Standards Canada](https://accessible.canada.ca/form/gc)

**Acceptance criteria**
- [ ] save state provides equal service in French and English.
- [ ] save state works on Chrome, Firefox, Edge, Safari, and Opera.
- [ ] unsuccessful saves provide error messages
- [ ] save states can be completed using a screen reader.
- [ ] buttons observe colour contrast requirements. 
- [ ] manual accessibility testing meet WCAG 2.1 AA requirements.
- [ ] risk register is updated to reflect new risks and their treatments. Treatments are implemented or a new card is created.

**Future considerations / Out of scope**
- How saving progress works with paginated forms
- Saving progress in an authenticated
