### ISSUE TITLE
API testing: Design updates

### ISSUE THREAD

**Issue by connorscarolyns** [cds-snc/platform-forms-client#4716]
The settings page could use some more fitness:

- [x] Change the order of radios to email, download, API #4731 
- [x] Have the download radio selected after deletion to make it clear that this is now the default #4724
- [x] Make the info banner at the top of the page match the style of the delete API key one.
- [x] Add a mb-20 between each section to visually separate them a bit more.
- [x] The sub text on the API radio is a different size - It should probably have the same classes as the highlighted span: #4737 
<img width="770" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1B5Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a66543fb1bdee097d317ae7e42ab1396fba83ae/image.png" alt="image.png" />

- [x] Place the API key ID tool tip after "API key ID" rather than the number itself.

<img width="528" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVh1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c4ff44e9eba4715e6a44518c7911d0b6331b3828/image.png" alt="image.png" />

**Comment by anikbrazeau** [comment]
Related #4731 #4724 #4737

**Comment by timarney** [comment]
PR 

https://github.com/cds-snc/platform-forms-client/pull/4754

**Comment by timarney** [comment]
Merged.
