### ISSUE TITLE
Protected B Form response retrieval (Complete solution)

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#568]
**Decision** from [scoping protected B work](https://github.com/cds-snc/platform-forms-client/issues/302).

**Action:** Create a prototype of a user interface to download form responses

[Link to opportunity canvas](https://github.com/cds-snc/platform-forms-client/issues/302)

**Epic Tasks**

- [x] Identify and create any research tasks if required for this feature. 
  - [See issue 529](https://app.zenhub.com/workspaces/gcforms-60cb8929764d71000e481cab/issues/cds-snc/platform-forms-client/529)
  - [See data accessibility testing findings](https://docs.google.com/presentation/d/15E846YgXHPwv1wTVhI5F3agcKlyW6OQcnSSDKhwabHc/edit#slide=id.g86d0a40fee_0_0)
- [x] Identify and create any policy implications or questions related to this feature. See questions in the opportunity canvas.
- [x] Review research and take core findings as basis for feature design
- [x] Create [Design Document (draft)](https://docs.google.com/document/d/1RUgysJFq3I_8gEbUE-3Wrb6BqsRcLKElfYyRWHjQ_9s/edit#) that clearly identifies how this feature will be implemented and seek Form's Community feedback.
- [x] Create development tasks as Issues
- [x] Make Epic focus of Sprint(s)
- [x] Release!
