### ISSUE TITLE
Response retrieval interface

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#729]
**Epic Description**
The download UI supports government users associated with a Form in retrieving their form responses. It does not include the output of the form response.

At a high level, the retrieval UI must to:
- [x] Support program admins in accessing their form response
- [x] Support program admins in confirming they have accessed and checked their response
- [x] Support program admins in reporting a problem to the GC Forms team with accessing a response before they have marked it as accessed and checked
- [x] Provide a secure way for program admins to login
- [x] Meet the required security controls associated with account management, audit events, continuous monitoring, contingency planning, security testing and evaluation. Specific controls will be outlined in cards and acceptance criteria
- [x] Meet at minimum WCAG 2.0 AA
- [x] Provides equal service in French and English.
- [x] Works on **Edge**, Firefox, and Chrome.
- [x] Key tasks can be completed using a screen reader.
- [x] Retrieval UI is updated to reflect new risks and their treatments. Treatments are implemented or a new card is created.

Depending on the likelihood of meeting the June 24th milestone, the retrieval UI should:
- [ ] Provide visibility for program administrators into actions the system is taking
- [ ] Be reviewed by a third-party for accessibility issues.
- [ ] Support downloading more than 10 files at a time

**Epic context**
[Design document for the solution](https://docs.google.com/document/d/1RUgysJFq3I_8gEbUE-3Wrb6BqsRcLKElfYyRWHjQ_9s/edit#)
[Link to ideation session and notes for the retrieval UI](https://miro.com/app/board/uXjVOBIUldg=/?moveToWidget=3458764522267174613&cot=10)
[Data processing and UI retrieval testing findings](https://docs.google.com/presentation/d/1r8L2H-CEB5p6BEkU376xQAfPmOcQseDu/edit#slide=id.p1)
[GC Forms ITSG-33 controls (all)](https://docs.google.com/spreadsheets/d/11h2vShehHparCyQ7VNCQ2qC-_h5jU8ZD/edit#gid=1278318464&fvid=1325969633)

**Comment by srtalbot** [comment]
@bryan-robitaille @connorscarolyns @sarahhobson - ready for review. 

This is the epic for the UI work. Will start on card definition for the checklist items above. Some of the items will be applicable in the acceptance criteria and not necessarily get their own card.
