### ISSUE TITLE
Retrieval UI Login

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/platform-forms-client#796]
**User story**: Persona based
As a program administrator
I need to be able to login to GC forms
So that I can access my form responses

As a program administrator
I need to be able to get support if I forget my login information
So that I can access my form responses

**Story context**
The goal is to create a minimum login experience that support a protected B login. The security requirements that need to be scoped in cover multiple ITSG-33 families, see the controls below. 

[GC Forms Security Requirements Traceability Matrix](https://docs.google.com/spreadsheets/d/11h2vShehHparCyQ7VNCQ2qC-_h5jU8ZD/edit#gid=1278318464)

**Acceptance criteria**
- [x] login provides equal service in French and English.
- [x] login works on Chrome, Firefox, and Edge.
- [x] (for discussion) login provides and auto-fill response if the field is saved on the end-users browser.
- [x] login provides error messages and validation.
- [x] login can be completed using a screen reader.
- [x] manual accessibility testing meet WCAG 2.1 AA requirements.
- [x] risk register is updated to reflect new risks and their treatments. Treatments are implemented or a new card is created.
- [x] login event is audited
- [ ] user can do a self serve credential reset
- [x] Exponential backoff retry
- [x] Session max age 2 hours / Refetch (aka check session state) every 30 min
- [x] Program administrator account cannot access "Super Admin" pages

**Related ITSG-33 controls**
See dependency cards
