### ISSUE TITLE
Form builder - preview functionality

### ISSUE THREAD

**Issue by Abi-Nada** [cds-snc/platform-forms-client#963]
[Co-design mock-ups](https://miro.com/app/board/uXjVOgSVHE8=/)

### User stories
As a form builder I can:
- Preview the created form questions
- Have the ability to see error states
- Observe the form flow

### Acceptance criteria:
- [x] Wireframes for the feature
- [x] Implement functionality
- [x] Going to and from Markdown to Rich Text
- [x] Ensuring keyboard nav works as expected
- [x] Ensuring the form preview and JSON output work as expected

### Out of scope:
Getting the data from your form into an email inbox

**Comment by timarney** [comment]
https://github.com/cds-snc/platform-forms-client/pull/1023

https://github.com/cds-snc/platform-forms-client/pull/1060
