### ISSUE TITLE
Outline and implement support processes

### ISSUE THREAD

**Issue by srtalbot** [cds-snc/platform-forms-client#973]
## Overall acceptance criteria
- [x] Create form for general support
- [x] Create form for go-live request
- [x] Create a password reset path (needs to be manual at this time) cc: @Moro-Code 
- [x] Integrate and test with freshdesk
- [x] Create support documentation so Ramya's team can action the tickets
- [x] Create list of CDS-facing documentation for support agents only
- [ ] Schedule 3 month survey for registered GC Forms users

## "Contact-us" Form acceptance criteria
- [x] [Draft form](https://www.figma.com/file/dbezuEglWNQ8qyO64eJJiA/v1.-Form-builder?node-id=2065%3A14014&t=ZkqN5VHLpTRpKAST-0)
- [x] Identify and implement privacy statement
- [x] Identify form entry path(s)
- [x] Identify form exit path(s)
- [x] Write support documentation and review with Growth
- [x] Review and finalize draft
- [x] Translate
- [x] Identify new risks in the Forms [risk register](https://docs.google.com/spreadsheets/d/1AyDSS2pnGtHtEow4eXx8tRwmExK9lrQJ6WqRAZ0ElEA/edit#gid=0)

## Support Form acceptance criteria
- [x] [Draft form](https://forms-staging.cdssandbox.xyz/en/id/cl8kl7o3r034779vlxurj9yio )
- [x] Identify and implement privacy statement
- [x] Identify form entry path(s)
- [x] Identify form exit path(s)
- [x] Write support documentation and review with Ramya
- [x] Review and finalize draft
- [x] Translate
- [x] Identify new risks in the Forms [risk register](https://docs.google.com/spreadsheets/d/1AyDSS2pnGtHtEow4eXx8tRwmExK9lrQJ6WqRAZ0ElEA/edit#gid=0)

### Go live
- [x] Receive final form copy in FR and EN
- [x] Test email submissions of data
- [x] Risk treatment plans are complete - moderate or high risk is flagged and approved by Director of Platform
- [x] Update entry path(s)

## Go-live request form acceptance criteria
- [x] Draft form
- [x] Identify and implement privacy statement
- [x] Identify form entry path(s)
- [x] Identify form exit path(s)
- [x] Write support documentation and review with Ramya
- [x] Identify new risks in the Forms [risk register](https://docs.google.com/spreadsheets/d/1AyDSS2pnGtHtEow4eXx8tRwmExK9lrQJ6WqRAZ0ElEA/edit#gid=0)

### Go live
- [x] Receive final form copy in FR and EN
- [x] Test email submissions of data
- [x] Risk treatment plans are complete - moderate or high risk is flagged and approved by Director of Platform
- [x] Update entry path(s)

**Comment by Abi-Nada** [comment]
SR to connect with Ramya

**Comment by srtalbot** [comment]
Draft support form: https://forms-staging.cdssandbox.xyz/en/id/cl8kl7o3r034779vlxurj9yio 

This form will need to be imbedded, but the content is good for a first pass. Need to review the entry links to the form to write support actions for Ramya's team.

**Comment by srtalbot** [comment]
For the draft go-live form we are asking for:
- Their program goals
- The email address of their service owner (the person responsible for the person building the form and back-up if they leave)

[Here is docs for the go-live process in freshdesk](https://cds-snc.freshdesk.com/a/solutions/articles/61000303754?lang=en&portalId=61000000728)

**Comment by srtalbot** [comment]
Freshdesk documentation: https://cds-snc.freshdesk.com/a/solutions/articles/61000303752/edit?lang=en&portalId=61000000728
